name: CI-CD FLASK Docker

on:
  push:
    branches: [main]

jobs:
  cd:
    name: docker build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t soumiakh/flask_devops_demo:latest .

      - name: Push Docker image
        run: docker push soumiakh/flask_devops_demo:latest

      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
          "powershell -ExecutionPolicy Bypass -File 'C:\\Users\\pc\\Desktop\\TPCDSSH\\deploy.ps1' -DockerUser ${{ secrets.DOCKERHUB_USERNAME }} -DockerToken ${{ secrets.DOCKERHUB_TOKEN }}"